#!/bin/bash
#SBATCH --job-name=ecg_ssp
#SBATCH --partition=brainlife
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4           # number of cores; adjust based on compute needs
#SBATCH --time=02:00:00              # 2 hours walltime
#SBATCH --mem-per-cpu=8G             # memory per CPU; adjust as needed

#SBATCH --output=slurm-%j.out
#SBATCH --error=slurm-%j.err


set -x
set -e

# Make output directories
mkdir -p out_dir
mkdir -p out_report
mkdir -p out_figs

singularity exec docker://brainlife/mne:1.2.1 python3 main.py


